/**
 * api/config-js.js
 * ================
 * Vercel Serverless Function — serves /config.js at runtime.
 *
 * Injects BOT_API_URL from Vercel environment variables into
 * window.__CONFIG__ so the dashboard can find the backend without
 * a rebuild.
 *
 * VERCEL SETUP
 * ─────────────
 * In Vercel → Project → Settings → Environment Variables, add:
 *
 *   BOT_API_URL   https://api.stoatmod.com     (official hosted backend)
 *   ENVIRONMENT   production                   (or "development" for previews)
 *
 * Self-hosters override the backend at runtime via the ?api= query param
 * on the dashboard URL — no change to this file needed.
 */

export default function handler(req, res) {
  // Read env vars — these are substituted at request time by Vercel
  const rawUrl = (process.env.BOT_API_URL || 'https://api.stoatmod.com').trim();
  const env    = process.env.ENVIRONMENT   || 'production';

  // Sanitise: strip trailing slash, reject anything that would break out of
  // a JS string literal (angle brackets, quotes, backslashes)
  const botApiUrl   = rawUrl.replace(/['"\\<>`]/g, '').replace(/\/$/, '');
  const environment = ['development', 'staging', 'production'].includes(env)
    ? env : 'production';

  const js = [
    '/* StoatMod runtime config — generated by /api/config-js */',
    `window.__CONFIG__ = {`,
    `  BOT_API_URL:  ${JSON.stringify(botApiUrl)},`,
    `  ENVIRONMENT:  ${JSON.stringify(environment)},`,
    `};`,
    '',
  ].join('\n');

  res.setHeader('Content-Type',  'application/javascript; charset=utf-8');
  res.setHeader('Cache-Control', 'no-store');
  res.status(200).send(js);
}
